export interface AppTheme {
  id: string;
  name: string;
  emoji: string;
  light: {
    primary: string;
    primaryForeground: string;
    secondary: string;
    secondaryForeground: string;
    accent: string;
    accentForeground: string;
    success: string;
    muted: string;
    border: string;
    input: string;
    background: string;
    card: string;
  };
  dark: {
    primary: string;
    primaryForeground: string;
    secondary: string;
    secondaryForeground: string;
    accent: string;
    accentForeground: string;
    success: string;
    muted: string;
    border: string;
    input: string;
    background: string;
    card: string;
  };
}

export const THEMES: AppTheme[] = [
  {
    id: 'ocean',
    name: 'المحيط الأزرق',
    emoji: '🌊',
    light: {
      primary: '#1B3A7A',
      primaryForeground: '#FFFFFF',
      secondary: '#EAF0FB',
      secondaryForeground: '#1B3A7A',
      accent: '#2563EB',
      accentForeground: '#FFFFFF',
      success: '#16A34A',
      muted: '#E4EAF5',
      border: '#D0D9EC',
      input: '#E8EDF8',
      background: '#F4F6FA',
      card: '#FFFFFF',
    },
    dark: {
      primary: '#3B62C4',
      primaryForeground: '#FFFFFF',
      secondary: '#0A1530',
      secondaryForeground: '#BDD0FF',
      accent: '#4B7BF5',
      accentForeground: '#FFFFFF',
      success: '#22C55E',
      muted: '#0A1530',
      border: '#132040',
      input: '#0A1530',
      background: '#050B1A',
      card: '#0D1E3D',
    },
  },
  {
    id: 'forest',
    name: 'الغابة الخضراء',
    emoji: '🌲',
    light: {
      primary: '#166534',
      primaryForeground: '#FFFFFF',
      secondary: '#DCFCE7',
      secondaryForeground: '#166534',
      accent: '#22C55E',
      accentForeground: '#FFFFFF',
      success: '#15803D',
      muted: '#D1FAE5',
      border: '#A7F3D0',
      input: '#ECFDF5',
      background: '#F0FDF4',
      card: '#FFFFFF',
    },
    dark: {
      primary: '#22C55E',
      primaryForeground: '#052E16',
      secondary: '#052E16',
      secondaryForeground: '#86EFAC',
      accent: '#4ADE80',
      accentForeground: '#052E16',
      success: '#4ADE80',
      muted: '#052E16',
      border: '#14532D',
      input: '#052E16',
      background: '#020C07',
      card: '#071A0C',
    },
  },
  {
    id: 'sunset',
    name: 'غروب الشمس',
    emoji: '🌅',
    light: {
      primary: '#C2410C',
      primaryForeground: '#FFFFFF',
      secondary: '#FFF7ED',
      secondaryForeground: '#C2410C',
      accent: '#F97316',
      accentForeground: '#FFFFFF',
      success: '#16A34A',
      muted: '#FFEDD5',
      border: '#FED7AA',
      input: '#FFF7ED',
      background: '#FFFAF5',
      card: '#FFFFFF',
    },
    dark: {
      primary: '#F97316',
      primaryForeground: '#431407',
      secondary: '#431407',
      secondaryForeground: '#FDBA74',
      accent: '#FB923C',
      accentForeground: '#431407',
      success: '#22C55E',
      muted: '#431407',
      border: '#7C2D12',
      input: '#431407',
      background: '#160800',
      card: '#1C0D00',
    },
  },
  {
    id: 'rose',
    name: 'الوردي الدافئ',
    emoji: '🌹',
    light: {
      primary: '#BE123C',
      primaryForeground: '#FFFFFF',
      secondary: '#FFF1F2',
      secondaryForeground: '#BE123C',
      accent: '#E11D48',
      accentForeground: '#FFFFFF',
      success: '#16A34A',
      muted: '#FFE4E6',
      border: '#FECDD3',
      input: '#FFF1F2',
      background: '#FFF5F5',
      card: '#FFFFFF',
    },
    dark: {
      primary: '#FB7185',
      primaryForeground: '#4C0519',
      secondary: '#4C0519',
      secondaryForeground: '#FDA4AF',
      accent: '#F43F5E',
      accentForeground: '#4C0519',
      success: '#22C55E',
      muted: '#4C0519',
      border: '#881337',
      input: '#4C0519',
      background: '#160009',
      card: '#1F0010',
    },
  },
  {
    id: 'purple',
    name: 'العنابي الملكي',
    emoji: '🍇',
    light: {
      primary: '#7C3AED',
      primaryForeground: '#FFFFFF',
      secondary: '#F5F3FF',
      secondaryForeground: '#7C3AED',
      accent: '#8B5CF6',
      accentForeground: '#FFFFFF',
      success: '#16A34A',
      muted: '#EDE9FE',
      border: '#DDD6FE',
      input: '#F5F3FF',
      background: '#FAF8FF',
      card: '#FFFFFF',
    },
    dark: {
      primary: '#A78BFA',
      primaryForeground: '#2E1065',
      secondary: '#2E1065',
      secondaryForeground: '#C4B5FD',
      accent: '#8B5CF6',
      accentForeground: '#2E1065',
      success: '#22C55E',
      muted: '#2E1065',
      border: '#4C1D95',
      input: '#2E1065',
      background: '#0D0520',
      card: '#150A30',
    },
  },
  {
    id: 'teal',
    name: 'الفيروزي البارد',
    emoji: '🌊',
    light: {
      primary: '#0F766E',
      primaryForeground: '#FFFFFF',
      secondary: '#F0FDFA',
      secondaryForeground: '#0F766E',
      accent: '#14B8A6',
      accentForeground: '#FFFFFF',
      success: '#16A34A',
      muted: '#CCFBF1',
      border: '#99F6E4',
      input: '#F0FDFA',
      background: '#F5FFFE',
      card: '#FFFFFF',
    },
    dark: {
      primary: '#2DD4BF',
      primaryForeground: '#042F2E',
      secondary: '#042F2E',
      secondaryForeground: '#5EEAD4',
      accent: '#14B8A6',
      accentForeground: '#042F2E',
      success: '#22C55E',
      muted: '#042F2E',
      border: '#134E4A',
      input: '#042F2E',
      background: '#010E0D',
      card: '#041A19',
    },
  },
  {
    id: 'golden',
    name: 'الذهبي الفاخر',
    emoji: '✨',
    light: {
      primary: '#92400E',
      primaryForeground: '#FFFFFF',
      secondary: '#FFFBEB',
      secondaryForeground: '#92400E',
      accent: '#D97706',
      accentForeground: '#FFFFFF',
      success: '#16A34A',
      muted: '#FEF3C7',
      border: '#FDE68A',
      input: '#FFFBEB',
      background: '#FFFCF0',
      card: '#FFFFFF',
    },
    dark: {
      primary: '#FBBF24',
      primaryForeground: '#451A03',
      secondary: '#451A03',
      secondaryForeground: '#FCD34D',
      accent: '#F59E0B',
      accentForeground: '#451A03',
      success: '#22C55E',
      muted: '#451A03',
      border: '#78350F',
      input: '#451A03',
      background: '#120A00',
      card: '#1C1000',
    },
  },
  {
    id: 'cherry',
    name: 'زهر الكرز',
    emoji: '🌸',
    light: {
      primary: '#9D174D',
      primaryForeground: '#FFFFFF',
      secondary: '#FDF2F8',
      secondaryForeground: '#9D174D',
      accent: '#EC4899',
      accentForeground: '#FFFFFF',
      success: '#16A34A',
      muted: '#FCE7F3',
      border: '#FBCFE8',
      input: '#FDF2F8',
      background: '#FFF5FB',
      card: '#FFFFFF',
    },
    dark: {
      primary: '#F472B6',
      primaryForeground: '#500724',
      secondary: '#500724',
      secondaryForeground: '#F9A8D4',
      accent: '#EC4899',
      accentForeground: '#500724',
      success: '#22C55E',
      muted: '#500724',
      border: '#831843',
      input: '#500724',
      background: '#160010',
      card: '#200018',
    },
  },
  {
    id: 'midnight',
    name: 'منتصف الليل',
    emoji: '🌙',
    light: {
      primary: '#1E293B',
      primaryForeground: '#FFFFFF',
      secondary: '#F1F5F9',
      secondaryForeground: '#1E293B',
      accent: '#334155',
      accentForeground: '#FFFFFF',
      success: '#16A34A',
      muted: '#E2E8F0',
      border: '#CBD5E1',
      input: '#F1F5F9',
      background: '#F8FAFC',
      card: '#FFFFFF',
    },
    dark: {
      primary: '#94A3B8',
      primaryForeground: '#0F172A',
      secondary: '#0F172A',
      secondaryForeground: '#CBD5E1',
      accent: '#64748B',
      accentForeground: '#F8FAFC',
      success: '#22C55E',
      muted: '#0F172A',
      border: '#1E293B',
      input: '#0F172A',
      background: '#020617',
      card: '#0D1B2A',
    },
  },
  {
    id: 'indigo',
    name: 'النيلي العميق',
    emoji: '💙',
    light: {
      primary: '#3730A3',
      primaryForeground: '#FFFFFF',
      secondary: '#EEF2FF',
      secondaryForeground: '#3730A3',
      accent: '#4F46E5',
      accentForeground: '#FFFFFF',
      success: '#16A34A',
      muted: '#E0E7FF',
      border: '#C7D2FE',
      input: '#EEF2FF',
      background: '#F5F7FF',
      card: '#FFFFFF',
    },
    dark: {
      primary: '#818CF8',
      primaryForeground: '#1E1B4B',
      secondary: '#1E1B4B',
      secondaryForeground: '#A5B4FC',
      accent: '#6366F1',
      accentForeground: '#1E1B4B',
      success: '#22C55E',
      muted: '#1E1B4B',
      border: '#312E81',
      input: '#1E1B4B',
      background: '#07061A',
      card: '#0F0E28',
    },
  },
];

export const DEFAULT_THEME_ID = 'ocean';

export function getThemeById(id: string): AppTheme {
  return THEMES.find((t) => t.id === id) ?? THEMES[0];
}
